apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-pool
spec:
  template:
    metadata:
      labels:
        # Exposes the accelerator label to allow pod placement targeting GPUs
        accelerator: nvidia-gpu
    spec:
      expireAfter: 720h
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"] # Provision cheap Spot instances to leverage credits
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["g4dn.xlarge", "g4dn.2xlarge", "g6.xlarge"] # Limit to NVIDIA T4 (g4dn) or NVIDIA ["g6.xlarge"] (more expensive)
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu-pool
      # Taints are critical to prevent regular CPU pods from scheduling on expensive GPU instances
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: NoSchedule
  limits:
    # Restrict the maximum vCPUs and VRAM available to this pool to protect against runaway costs
    cpu: 8
    memory: 32Gi
    nvidia.com/gpu: 2
  disruption:
    # Actively consolidate and terminate empty/underutilized GPU nodes to save costs
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
